# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  USERNAME:
    sh: whoami
  HOME:
    sh: echo $HOME
  SOPS_CONFIG_DIR: '{{.HOME}}/.config/sops/age'
  SOPS_KEY_FILE: '{{.SOPS_CONFIG_DIR}}/keys.txt'
  SOPS_KEY_PUB: 'secrets/sops-key-{{.USERNAME}}.pub'

includes:
  hostkeys: tasks/Taskfile.hostkeys.yml
  terraform: tasks/Taskfile.terraform.yml
  secrets: tasks/Taskfile.secrets.yml
  ansible: tasks/Taskfile.ansible.yml
  server: tasks/Taskfile.server.yml
  tunnel: tasks/Taskfile.tunnel.yml
  backup: tasks/Taskfile.backup.yml
  test: tasks/Taskfile.test.yml
  registry: tasks/Taskfile.registry.yml
  app: tasks/Taskfile.app.yml

tasks:
  default:
    desc: Show available commands
    cmds:
      - task: help

  help:
    desc: Show help message
    silent: true
    cmds:
      - |
        echo "Infrastructure as Code"
        echo ""
        echo "Terraform commands:"
        echo "  task terraform:init    -- <workspace>  # Initialize workspace (dev or prod)"
        echo "  task terraform:plan    -- <workspace>  # Plan changes (dev or prod)"
        echo "  task terraform:apply   -- <workspace>  # Apply changes (dev or prod)"
        echo "  task terraform:destroy -- <workspace>  # Destroy resources (dev or prod)"
        echo "  task terraform:output  -- <workspace>  # Show outputs (dev or prod)"
        echo ""
        echo "Ansible commands:"
        echo "  task ansible:install                   # Install required collections"
        echo "  task ansible:bootstrap -- <workspace>  # One-time bootstrap as root (dev or prod)"
        echo "  task ansible:run       -- <workspace>  # Configure server (Docker, Traefik, security)"
        echo ""
        echo "Application Deployment:"
        echo "  task app:deploy   -- <env> <sha>       # Deploy application to dev or prod"
        echo "  task app:versions -- <env>             # List available image versions"
        echo ""
        echo "Testing:"
        echo "  task test:run                          # Run all tests (validate, format check, security scan)"
        echo ""
        echo "SSH Tunnel:"
        echo "  task tunnel:start -- <workspace>       # Start SSH tunnel (dev or prod)"
        echo "  task tunnel:stop  -- <workspace>       # Stop SSH tunnel (dev or prod)"
        echo ""
        echo "Secrets Management (SOPS):"
        echo "  task secrets:keygen                    # Generate age key pair"
        echo "  task secrets:generate-sops-config      # Generate .sops.yaml"
        echo ""
        echo "Registry:"
        echo "  task registry:overview                 # List tags (TAG, CREATED, DESCRIPTION) for all repos"
        echo ""
        echo "Utilities:"
        echo "  task server:observe -- <dev|prod> <cmd>  # Run read-only command on server (observer); use for investigation"
        echo "  task server:check-status                 # Check if servers are up (checks both dev and prod)"
        echo "  task server:list-hetzner-keys            # List Hetzner SSH keys with IDs"
        echo ""
        echo "Backups (Hetzner):"
        echo "  task backup:list           -- <dev|prod>             # List backup images"
        echo "  task backup:restore        -- <dev|prod> <image-id>  # Restore from backup (destructive)"
        echo "  task backup:restore-latest -- <dev|prod>             # Restore from latest backup (destructive)"

  # Internal validation tasks - used by other tasks via deps or direct calls
  _check:sops-key:
    desc: "(internal) Ensure SOPS key exists"
    internal: true
    preconditions:
      - sh: test -f "{{.SOPS_KEY_FILE}}"
        msg: "SOPS key file not found. Run 'task secrets:keygen' first."

  _check:workspace:
    desc: "(internal) Validate workspace argument (dev|prod)"
    internal: true
    preconditions:
      - sh: '[ -n "{{.WORKSPACE}}" ]'
        msg: "Workspace required. Usage: task {{.TASK_NAME}} -- <dev|prod>"
      - sh: '[ "{{.WORKSPACE}}" = "dev" ] || [ "{{.WORKSPACE}}" = "prod" ]'
        msg: "Invalid workspace '{{.WORKSPACE}}'. Use: dev or prod"

