# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  deploy:
    desc: "Deploy Prefect flows (use: task workflow:deploy)"
    dir: ansible
    silent: true
    cmds:
      - task: :_ansible:install
      - |
        echo "🔄 Deploying Prefect flows to platform..."
        IP=$(task hostkeys:ip -- platform) || exit 1
        ansible-playbook -i "platform," playbooks/prefect-deploy.yml -e "ansible_host=${IP}"
