# Ansible Inventory
# This file is automatically generated by Terraform from main.tf
# DO NOT EDIT MANUALLY - changes will be overwritten
# 
# To regenerate: terraform apply

[servers]
${server_name} ansible_host=${server_ip} ansible_user=${server_user}

[servers:vars]
ansible_python_interpreter=/usr/bin/python3

